// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API_KEY',
    appId: 'APP_ID',
    messagingSenderId: '447970992345',
    projectId: 'bydeliverymovel',
    authDomain: 'bydeliverymovel.firebaseapp.com',
    storageBucket: 'bydeliverymovel.appspot.com',
    measurementId: 'G-W5877ZBS96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API_KEY',
    appId: 'APP_ID',
    messagingSenderId: '447970992345',
    projectId: 'bydeliverymovel',
    storageBucket: 'bydeliverymovel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API_KEY',
    appId: 'APP_ID',
    messagingSenderId: '447970992345',
    projectId: 'bydeliverymovel',
    storageBucket: 'bydeliverymovel.appspot.com',
    iosClientId: '447970992345-95f44cgc927tjvn7l06polc90qrp048b.apps.googleusercontent.com',
    iosBundleId: 'com.example.bydelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
     apiKey: 'API_KEY',
    appId: 'APP_ID',
    messagingSenderId: '447970992345',
    projectId: 'bydeliverymovel',
    storageBucket: 'bydeliverymovel.appspot.com',
    iosClientId: '447970992345-bmnck0k38f26i6vi3su6tf7q5cnf2l3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.bydelivery.RunnerTests',
  );
}
